oldNum = input("Please enter your number:\n")
oldDigits = input("\nPlease provide a digit string for the number system used by your number (E.G: '0123456789' for normal numbers):\n")
oldBase = len(oldDigits)
newDigits = input("\nPlease provide a digit string for the number you would like it to be converted to (E.G: 0123456789abcdef for hexadecimal):\n")
newBase = len(newDigits)
